# Generated by Django 4.2.3 on 2023-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib_webapp', '0003_alter_fibonaccitable_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibonaccitable',
            name='id',
        ),
        migrations.AlterField(
            model_name='fibonaccitable',
            name='fib_no',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
